---
session:
  name: achievemore
  attach: true
template:
  direction: Vertical
  parts:
    - direction: Horizontal
      parts: 
        - direction: Vertical
          borderless: true
          split_size:
            Fixed: 1
          run:
            plugin:
              location: "zellij:tab-bar"

        - direction: Vertical
          body: true

        - direction: Vertical
          borderless: true
          split_size: 
            Fixed: 2
          run:
            plugin:
              location: "zellij:status-bar"
tabs:
  - name: "Angular"
    focus: true
    direction: Vertical
    run: 
      command: { cmd: vim, cwd: "/Volumes/Workspace/achievemore/achievemore-bundle/services/angular-frontend/" }
  - name: "Backbone"
    direction: Vertical
    run: 
      command: { cmd: vim, cwd: "/Volumes/Workspace/achievemore/achievemore-bundle/services/business-backbone/" }
  - name: "Backend"
    direction: Vertical
    run: 
      command: { cmd: vim, cwd: "/Volumes/Workspace/achievemore/achievemore-bundle/services/backend/" }
  - name: "Frontend"
    direction: Vertical
    run: 
      command: { cmd: vim, cwd: "/Volumes/Workspace/achievemore/achievemore-bundle/services/frontend/" }
  - name: "Docker"
    direction: Vertical
    run: 
      command: { cmd: lazydocker, cwd: "/Volumes/Workspace/achievemore/achievemore-bundle/" }
