---
session:
  # name: "mobile"
  attach: true

template:
  direction: Vertical
  parts:
    # - direction: Vertical
    #   # borderless: true
    #   split_size:
    #     Percent: 15
    #   run:
    #     plugin:
    #       location: "zellij:strider"

    - direction: Horizontal
      parts:
        - direction: Vertical  # part 1
          borderless: true
          split_size:
            Fixed: 1
          run:
            plugin:
              location: "zellij:tab-bar"

        - direction: Vertical # part 2
          body: true

        - direction: Vertical # part 3
          borderless: true
          split_size:
            Fixed: 2
          run:
            plugin:
              location: "zellij:status-bar"

tabs:
  - focus: true
    name: "VIM"
    parts:
      - direction: Vertical
        focus: true
        run:
          command: { cmd: fish, args: ["-c", "DISABLE_GREETING=1 vim"] }

      - direction: Horizontal
        split_size:
          Percent: 20
        run:
          command: { cmd: fish, args: ["-c", "DISABLE_GREETING=1 fish"] }

  - name: "Commands"
    direction: Horizontal
    parts:
      - direction: Horizontal
        focus: true
        run:
          command: { cmd: fish, args: ["-c", "DISABLE_GREETING=1 fish"] }

      # - direction: Horizontal
      #   run:
      #     command: { cmd: fish, args: ["-c", "top"] }
